# Generated by Django 4.2.4 on 2023-09-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_scriptinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptinfo',
            name='script_file',
            field=models.FileField(blank=True, upload_to='scripts/'),
        ),
        migrations.AlterField(
            model_name='scriptinfo',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
