# Generated by Django 4.2.4 on 2023-09-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_alter_scriptinfo_script_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptinfo',
            name='arguments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scriptinfo',
            name='execution_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scriptinfo',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
